In [1]:
from keras.models import load_model

model = load_model('myface_recognition.h5')

Using TensorFlow backend.


In [3]:
import cv2
import numpy as np


face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_detector(img, size=0.5):

    # Convert image to grayscale
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    if faces is ():
        return img, []

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h, x:x+w]
        roi = cv2.resize(roi, (224, 224))
    return img, roi


# Open Webcam
cap = cv2.VideoCapture(0)

while True:

    ret, frame = cap.read()

    image, face = face_detector(frame)

    face=np.array(face)
    face=np.expand_dims(face,axis=0)
    if face.shape==(1,0):
        cv2.putText(image,"I don't know", (100, 120), cv2.FONT_HERSHEY_COMPLEX, 1, (255,120,150), 2)
        cv2.imshow('Face Recognition',image)
    else:
        result=model.predict(face)
        print(result)
        if result[0][0] == 1.0:
            cv2.putText(image,"chakri", (100, 120), cv2.FONT_HERSHEY_COMPLEX, 1, (255,120,150), 2)
            cv2.imshow('Face Recognition',image)
        elif result[0][0] == 0.0:
            cv2.putText(image,"mahesh", (100, 120), cv2.FONT_HERSHEY_COMPLEX, 1, (255,120,150), 2)
            cv2.imshow('Face Recognition',image)
        else:
            cv2.putText(image,"Not recognized", (100, 120), cv2.FONT_HERSHEY_COMPLEX, 1, (255,120,150), 2)
            cv2.imshow('Face Recognition',image)

    if cv2.waitKey(1) == 13:
        break

cap.release()
cv2.destroyAllWindows()


[[0.9947937  0.00283737 0.0023689 ]]
[[0.9956013  0.00278384 0.00161488]]
[[0.9972652  0.00146705 0.00126774]]
[[0.996387   0.00220216 0.00141084]]
[[0.99518293 0.00313499 0.00168205]]
[[0.99535394 0.00306006 0.00158612]]
[[0.99657357 0.00203179 0.00139477]]
[[0.99708986 0.00157386 0.00133623]]
[[0.9954691  0.00289547 0.00163539]]
[[0.99494135 0.00296733 0.00209138]]
[[0.99604696 0.00219365 0.00175935]]
[[0.9955818  0.00280695 0.00161123]]
[[0.9955539  0.00296096 0.00148512]]
[[0.9953129  0.00261157 0.00207538]]
[[0.9966503  0.00198197 0.00136778]]
[[0.9971841  0.00145494 0.00136101]]
[[0.99592566 0.00245521 0.00161919]]
[[0.9967295  0.00181333 0.00145717]]
[[0.9961565  0.0021398  0.00170377]]
[[0.9958246  0.00226221 0.00191328]]
[[0.9959777  0.00211124 0.00191107]]
[[0.99729294 0.00146099 0.00124605]]
[[0.99489117 0.00285313 0.00225568]]
[[0.9953067  0.00277134 0.00192204]]
[[0.9953496  0.00298279 0.00166765]]
[[0.9955206  0.00258758 0.00189177]]
[[0.9950871  0.00280733 0.00210561]]
[

[[0.9923098  0.00431874 0.00337143]]
[[0.9970853  0.00151677 0.00139792]]
[[0.996548   0.00185808 0.00159389]]
[[0.9962353  0.00226352 0.00150113]]
[[0.9976252  0.00128079 0.00109396]]
[[9.9774832e-01 1.2862606e-03 9.6544554e-04]]
[[0.99735117 0.00157684 0.00107193]]
[[0.9968322  0.00205598 0.00111183]]
[[0.9966834  0.00158926 0.00172733]]
[[0.99786264 0.00105328 0.00108409]]
[[0.99621695 0.00202187 0.00176121]]
[[0.9972139  0.00130436 0.00148184]]
[[0.997357   0.00138383 0.00125927]]
[[0.9977495  0.00115406 0.00109644]]
[[0.9971732  0.00146448 0.00136226]]
[[0.99719596 0.00162725 0.00117672]]
[[0.99612206 0.00226073 0.00161718]]
[[0.99586403 0.00209049 0.00204543]]
[[0.996384   0.00223304 0.00138292]]
[[0.9959567  0.00232859 0.00171471]]
[[0.9970182  0.00178758 0.00119425]]
[[0.9969446  0.00158536 0.00147005]]
[[0.99793446 0.00106093 0.0010046 ]]
[[0.99755365 0.00136147 0.00108488]]
[[9.9793530e-01 1.2316098e-03 8.3308434e-04]]
[[0.99749666 0.00140239 0.00110093]]
[[0.9977551  0.00118